### ISSUE TITLE
Update to use the newest version (0.3.0) of the SDK?

### ISSUE THREAD

**Issue by lautrr** [harness/ff-elixir-server-sample#1]
Hi.

Thanks for making this sample project.

Can this be updated to use the newest version of the SDK, please?

**Comment by erdirowlands** [comment]
Hi @lautrr 

Thank you for opening this issue and sorry for getting back to you so late. I wasn't watching for Issues on this repo - I've fixed that now!

Sure thing. The SDK has been updated to `0.4.0-beta.2` 

Any questions or issues, please let me know: erdi.rowlands@harness.io

Thanks
